# Generated by Django 4.2.11 on 2024-04-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('cargo', models.CharField(choices=[('voluntário', 'Voluntário'), ('cuidador', 'Cuidador'), ('admin', 'Admin')], max_length=15)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
