# Generated by Django 4.2.11 on 2024-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=10)),
                ('raca', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=10)),
                ('castrado', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('doencas_existentes', models.TextField(blank=True)),
                ('adotado', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastro de animais',
                'ordering': ['-data'],
            },
        ),
    ]
