# Generated by Django 4.2.11 on 2024-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0002_alter_animal_options_remove_animal_adotado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=20),
        ),
    ]
