# Generated by Django 4.2.11 on 2024-03-29 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0007_alter_animal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Cadastro de animais'},
        ),
        migrations.AddField(
            model_name='animal',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='animal',
            name='doencas_existentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='porte',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='vacinado',
            field=models.BooleanField(default=False),
        ),
    ]
