# Generated by Django 4.2.11 on 2024-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalhesanimal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
