# Generated by Django 4.2.11 on 2024-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalhesanimal', '0005_cadastro_animais_delete_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_animais',
            name='foto',
            field=models.ImageField(blank=True, upload_to='animal_photos/'),
        ),
    ]
